import Head from 'next/head';
import { useState } from 'react';
import { useRouter } from 'next/router';

export default function Home() {
  const router = useRouter();
  const [secret, setSecret] = useState('');

  return (
    <>
      <Head>
        <title>Stripe Checkout</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div
          style={{
            width: '100%',
            height: '90vh',
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'center',
            alignItems: 'center',
            gap: 20,
          }}
        >
          <input
            style={{
              height: '32px',
              minWidth: '400px',
              padding: '5px',
              fontSize: '20px',
            }}
            placeholder="Enter stripe client secret here..."
            value={secret}
            onChange={(e) => setSecret(e.target.value)}
          />
          <button
            style={{ maxWidth: '200px' }}
            onClick={() => router.push(`/${secret}`)}
          >
            Go to checkout
          </button>
        </div>
      </main>
    </>
  );
}
